---
title: "L5 homework"
author: "Atiya Shehreen"
date: "2025-06-04"
output: html_document
---


# 1. Gene Expression Classifier using for loops and conditionals
```{r}
genes <- c("TP53", "EGFR", "MYC", "BRCA2")
expr <- c(4.8, 6.3, 11.7, 9.5)
for (i in 1:length(genes)) {
  status <- if (expr[i] > 10) "High"
  else if (expr[i] > 6) "Moderate"
  else "Low"
  cat(genes[i], "has", status, "expression\n")
}
```
# 2. Sample Screeing: Skipping Bad Samples using next
```{r}
samples <- c("good", "bad", "good", "contaminated", "good", "bad")
for (x in samples) {
  if (x == "bad") next
  print(paste("Sample", x, "is flagged for analysis" ))
}
```

# 3. Stopping at Contaminated Samples using break
```{r}
samples <- c("good", "bad", "good", "contaminated", "good", "bad")
for (x in samples) {
  if (x == "contaminated") {
    print("Contamination detected. Halting...")
    break
  }
  print(paste("Analyzing Sample", x))
}

```

# 4. Sample prep countdown using while loop
```{r}
i = 1
while (i <= 5) {
  cat("Sample", i, "is ready for analysis\n")
  i = i + 1
}
```
# 5. 
```{r}
level <- 2
while (level <= 10) {
  increase <- runif(1, min = 0.5, max = 1.5)
  level <- level + increase
  print(paste("Current protein level:", level))
}
```

# 6. BMI function
```{r}
bmi_category <- function(weight, height) {
  bmi <- weight/(height^2)
  if (bmi < 18.5) {
    return("Underweight")
    } else if (bmi <= 24.9) {
      return("Normal")
    } else if (bmi <= 29.9) {
      return("Overweight")
    }
      else if (bmi >= 30) {
        return("Obese")
    }
}

bmi_category(65, 1.70)
```


# 7. Gene Risk Calculator
```{r}
gene_risk <- function(expr, mut_status) {
  if (expr > 9 & mut_status == "Yes") {
    return("High")
  } else if (expr > 6) {
    return("Moderate")
  } else 
    return("Low")
}

expr <- c(5.5, 10.1, 7.3)
mut_status <- c("No", "Yes", "No")

mapply(FUN = gene_risk, expr, mut_status)
```

# 8. for loop + Data frame
```{r}
df <- data.frame(
  genes = c("BRCA1", "TP53", "MYC", "HBA1"),
  expr_values = c(2.5, 8.7, 1.7, 11.2)
)

expr_status <- character(nrow(df))
for (i in 1:4) {
  expr_status[i] <- if (df$expr_values[i] > 10) "High"
  else if (df$expr_values[i] > 6) "Moderate"
  else "Low"
}

df$expression_status <- expr_status
print(df)
```

# 9. Function + Error Checking
```{r}
get_expression_level <- function(gene, df) {
 if (!gene %in% df$gene) {
    return("Gene not found")
 }
  expr_value <- df$expr[df$gene == gene]
if (expr_value > 8) {
  return("High")
} else if (expr_value > 6) {
  return("Medium")
} else {
  return("Low")
}
}
df <- data.frame(gene = c("TP53", "BRCA1"), expr = c(5.5, 10.5))
get_expression_level("BRCA1", df)
get_expression_level("EGFR", df)
```

